services:
  datawarehouse:
    image: postgres:13
    container_name: dwh_db
    hostname: datawarehouse
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=dwh123
      # - POSTGRES_DB=dvdrental_clean
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dwh_db:/var/lib/postgresql/data
    ports:
      - 3000:5432
volumes:
  dwh_db:
